VLAN tests wo traffic
PLVision/dent-testing pull request #11
Opened 2023-01-10 11:04 UTC by StepanVovkPLV

Tests:
 - test_max_vlans;
 - test_add_interface_to_vlan_wo_bridge
Signed-off-by: Stepan Vovk <stepan.vovk@plvision.eu>

2023-01-10 13:38 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_without_traffic.py
> +import json
We should not group tests based on the traffic-sending criteria. Tests should be grouped based on the feature.

2023-01-10 13:47 UTC, anton7811 requested changes

2023-01-10 13:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_without_traffic.py
> +async def test_max_vlans(testbed):
E.g. This one belongs to VLAN scaling.

2023-01-10 13:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_without_traffic.py
> +    4. Insert interface to all VLANs possible(4094)
space between "possible" and "4094"

2023-01-10 13:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_without_traffic.py
> +    tgen_dev, dent_devices = await tgen_utils_get_dent_devices_with_tgen(testbed, [], 1)
If you do not need traffic, there is no reason to set the number of links to 1.
Also you can use just tb_get_all_devices which doesn't require TG in test config at all.

2023-01-10 13:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_without_traffic.py
> +    await IpLink.add(input_data=[{device: [{"device": f"{test_port}", "type": "veth"}]}])
Why are you adding veth pairs?

2023-01-10 13:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_without_traffic.py
> +    out = await IpLink.set(input_data=[{device: [{"device": f"{test_port}", "operstate": "up"}]}])
You can combine this command with the next one on line 44.

2023-01-10 13:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_without_traffic.py
> +    Test Name: Add  interface to vlan without enslaving to bridge entity
Please remove extra space after "Add"
Also add some mark that this is negative test.

2023-01-10 13:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_without_traffic.py
> +    tgen_dev, dent_devices = await tgen_utils_get_dent_devices_with_tgen(testbed, [], 1)
See my comments above about using TG here.

2023-01-10 13:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_without_traffic.py
> +    out = await IpLink.add(input_data=[{device: [{"device": f"{test_port}", "type": "veth"}]}])
Please remove veth creation.

2023-01-12 14:29 UTC, anton7811 requested changes

2023-01-12 14:29 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_configuration_checks.py
> +    assert "RTNETLINK answers: Operation not supported" in out[0][device]["result"]
No new line at the end of the file. See PEP8

2023-01-12 14:29 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_configuration_checks.py
> +    test_port = dent_devices.links_dict[device][1][0]  # get first port from config
In fact, you might not have any port in config. It should be enough just to use "swpX"
But let's leave as is so far.

2023-01-12 14:29 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_configuration_checks.py
> +    await IpLink.set(input_data=[{device: [{"device": f"{test_port}", "master": "br0"},
You can do this in a single command:
`{"device": f"{test_port}", "master": "br0", "operstate": "up"}`
But yet again. In this particular case you can leave it as is

2023-01-12 14:29 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_configuration_checks.py
> +                                           {"device": f"{test_port}", "operstate": "up"}
Please do not use constructions like this `f"{test_port}"`
Here you substitute string to string with string to string conversion. Do just `{"device": test_port}`

2023-01-18 11:44 UTC, StepanVovkPLV commented
closing in favor of https://github.com/PLVision/dent-testing/pull/15

2023-01-18 11:44 UTC, closed without merging