Add policer tests
PLVision/dent-testing pull request #120
Opened 2023-05-02 06:32 UTC by StepanVovkPLV

Adds 16 policer tests

2023-05-02 13:36 UTC, SerhiyBoikoPLV requested changes

2023-05-02 13:36 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_basic_functionality.py
> +)
```suggestion
)

```

2023-05-02 13:36 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_basic_functionality.py
> +        'want_port': True if traffic_type in ['tcp', 'udp'] else None,
```suggestion
        'want_port': traffic_type in ['tcp', 'udp'],
```

2023-05-02 13:36 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_basic_functionality.py
> +                                              frame_rate_pps=100)
@SerhiyBoikoPLV will have to rename this to `frame_rate` or `packet_rate` sometime in the future, since `frame_rate_pps` might not refer to pps anymore

2023-05-02 13:36 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_negative_add_rule_to_bond.py
> +    not_offloaded = out[0][dent]['parsed_output'][1]['options']['not_in_hw']
you might get a `KeyError` exception here, use `.get()`:
```suggestion
    not_offloaded = out[0][dent]['parsed_output'][1]['options'].get('not_in_hw')
```

2023-05-02 13:36 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_negative_add_rule_to_bond.py
> +    not_offloaded = out[0][dent]['parsed_output'][1]['options']['not_in_hw']
Another issue is that I am not sure that you could rely on the order of rules that you get back from `TcFilter.show()`. It would be safer if you refer to rules by using their prio/pref:
```python
out = await TcFilter.show(input_data=[{dent: [
    {'dev': bond,
     'direction': 'ingress',
     'pref': rule_pref,  # <--
     'options': '-j'}
]}], parse_output=True)
not_offloaded = out[0][dent]['parsed_output'][0]['options'].get('not_in_hw')
```

2023-05-03 07:09 UTC, StepanVovkPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_basic_functionality.py
> +                                              frame_rate_pps=100)
but not in this PR, no?

2023-05-03 07:18 UTC, StepanVovkPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_negative_add_rule_to_bond.py
> +    not_offloaded = out[0][dent]['parsed_output'][1]['options']['not_in_hw']
I add only 1(one) rule

2023-05-04 10:57 UTC, yuriilisovskyi approved these changes

2023-05-04 10:57 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/policer/test_policer_basic_functionality.py
> +async def test_policer_basi_functionality(testbed, traffic_type, qdisc_type):
basic*

2023-05-05 09:20 UTC, closed without merging