Add lacp no traffic tests
PLVision/dent-testing pull request #135
Opened 2023-05-12 12:53 UTC by StepanVovkPLV

Signed-off-by: Stepan Vovk <stepan.vovk@plvision.eu>

2023-05-16 06:50 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_no_traffic.py
> +
No need for newline

2023-05-16 06:50 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_no_traffic.py
> +    assert out[0][device]['rc'] == 0, 'Fail to set port to up state'
to down state*

2023-05-31 07:21 UTC, yuriilisovskyi approved these changes

2023-05-31 09:59 UTC, SerhiyBoikoPLV requested changes

2023-05-31 09:59 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_no_traffic.py
> +    _, num_of_ports = await dent_devices[0].run_cmd('ifconfig  -a | grep -Eo "swp[0-9]+" | wc -l')
please also check `rc`

2023-05-31 09:59 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_no_traffic.py
> +        {'device': f'swp{idx+1}',
I would suggest getting the port list via `IpLink.show()`, and not using an `'swp'` string. The port on DUT might have a different naming convention (`sw1p1`).

2023-06-02 14:23 UTC, SerhiyBoikoPLV requested changes
please add `__init__.py` to `./functional/lacp/` folder, because otherwise pytest does not see these LACP tests

2023-06-14 08:59 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_no_traffic.py
> +         'master': f'bond_{port[0]}'} for port in enumerate(device_ports)]}])
```suggestion
         'master': f'bond_{idx}'} for idx, port in enumerate(device_ports)]}])
```

2023-06-14 09:04 UTC, SerhiyBoikoPLV requested changes

2023-06-14 09:04 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_no_traffic.py
> +    assert out[0][device]['rc'] == 0, f'Fail enslaving {max_ports_in_lag} ports to bond'
please change assert message, you are not enslaving any ports here

2023-06-14 09:04 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_no_traffic.py
> +    assert 'RTNETLINK answers: No space left on device' in out[0][device]['result'], 'Can enslave more ports to bond'
```suggestion
    assert 'RTNETLINK answers: No space left on device' in out[0][device]['result'], \
        'Failed to enslave ports to bond'
```

2023-06-14 09:04 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_no_traffic.py
> +    assert out[0][device]['rc'] == 0, 'Fail to set bond(s) to up state'
```suggestion
    assert out[0][device]['rc'] == 0, 'Fail to set ports to up state'
```

2023-06-14 10:49 UTC, SerhiyBoikoPLV approved these changes

2023-07-03 11:01 UTC, merged