Bridging: Add traffic to 1 test
PLVision/dent-testing pull request #14
Opened 2023-01-18 10:45 UTC by stavrukPLV

Signed-off-by: Kostiantyn Stavruk <kostiantyn.stavruk@plvision.eu>

2023-01-18 13:59 UTC, anton7811 requested changes

2023-01-18 13:59 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_no_fwd_port_down.py
> +import pytest
Please add __init__.py in this folder.

2023-01-18 13:59 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_no_fwd_port_down.py
> +import asyncio
And also add your variables in constants.py.
This will be your first PR with bridging tests. So let's have all these files here.

2023-01-18 13:59 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_no_fwd_port_down.py
> +    assert out[0][device_host_name]["rc"] == 0, f" Verify that ageing time set to '600', bridge and bridge entities set to 'UP' state and links enslaved to bridge.\n {out}"
Please remove extra space before " Verify" and " {out}"

2023-01-18 13:59 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_no_fwd_port_down.py
> +    await tgen_utils_stop_traffic(tgen_dev)
Do you verify that traffic passed?

2023-01-20 11:03 UTC, anton7811 requested changes

2023-01-20 11:03 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_no_fwd_port_down.py
> +        (ports[0], tg_ports[0], "12.0.0.1", "12.0.0.2", 24),
`swp ip` is redundant

2023-01-20 11:03 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_no_fwd_port_down.py
> +        (ports[1], tg_ports[1], "13.0.0.1", "13.0.0.2", 20),
`tg ip` should be in the same subnet.
E.g.: 11.0.0.N/24. Where N is port index.

2023-01-20 11:03 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_no_fwd_port_down.py
> +    10. Verify that entry not exist in mac table.
Please add note here and in the code: Check mac table only. No capturing since it's not possible on the port in DOWN state.

2023-01-20 11:03 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
> +    "suite_functional_bridging":"Functional bridging tests",
Missed space after ":"

2023-01-20 11:03 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
> +    "suite_group_functional":["suite_functional_bridging"],
Same here.

2023-01-26 15:05 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_admin_state_down_up.py
> +    unlearned_macs = [en["mac"] for en in fdb_entries if "mac" in en]
`learned_macs`

2023-01-26 15:06 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_admin_state_down_up.py
> +        assert float(row["Tx Frames"]) > 0.000, f'Failed>Ixia should transmit traffic: {row["Tx Frames"]}'
You can't send half of a frame. TX/RX frames will always be integers.

2023-01-26 22:19 UTC, SerhiyBoikoPLV reviewed
A lot of your tests have the same setup steps: creating a bridge -> setting bridge UP -> adding port to bridge -> setting learning to true and flooding to false. Maybe this should be moved in to a function? To `/functional/bridging/conftest.py` or `/utils/bridge_utils.py`.

2023-01-30 11:30 UTC, anton7811 requested changes

2023-01-30 11:30 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_ageing.py
> +@pytest.mark.asyncio
You can add those marks to line 19:
https://docs.pytest.org/en/7.1.x/example/markers.html#marking-whole-classes-or-modules

2023-01-30 11:30 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_ageing.py
> +    8.  Send traffic to swp1 with sourse mac aa:bb:cc:dd:ee:11.
What's for steps 8 and 9 ?

2023-01-30 11:30 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_ageing.py
> +    10. Send traffic to swp1 again with sourse mac aa:bb:cc:dd:ee:11 for refreshing br0
8. Send traffic.
9. Wait for 0.5-0.75 AT, and check that entry exists
10. Send traffic again, and check there is no flooding.
11. Wait for 0.9 AT and verify it still exists
12. Wait AT - entry should be deleted

NOTE: Remove disabling flooding in the test.

2023-01-30 11:30 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_ageing.py
> +    out = await IpLink.set(
Can you combine all IpLink.set() ?

2023-01-30 11:30 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_ageing.py
> +            "dstMac": "ff:ff:ff:ff:ff:ff",
send some unicast.

2023-01-30 11:30 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_ageing.py
> +    9.  Delaying for ageing_time seconds.
Delaying 3 AT

2023-01-30 11:30 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_ageing.py
> +    #await tgen_utils_stop_protocols(tgen_dev)
Stop protocols is required. But it could be a fixture from Yuriy.

2023-01-30 11:30 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_jumbo_frame.py
> +    10. Verify that address have been learned and forwarded.
Learning is disabled on step 6. HOW?

2023-01-30 11:30 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_jumbo_frame.py
> +    9.  Send traffic to swp1, swp2, swp3, swp4 with source macs
Please mention here what packet size do you use.

2023-01-30 11:30 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_jumbo_frame.py
> +    streams = {
I do not see that you send a jumbo frame. Where is the size?

2023-01-30 11:30 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_jumbo_frame.py
> +    6.  Set ports swp1, swp2, swp3, swp4 learning ON.
See step 9. Those are conflicting steps. To fix it read carefully your test purpose.

2023-01-30 11:30 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_jumbo_frame.py
> +            "protocol": "802.1Q",
Yet again - no size here

2023-01-30 11:30 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_jumbo_frame.py
> +    Test Overview: Verifying that Jambo frames of average size are not learned and not forwarded.
What does this mean? Why average size is not learned?

2023-02-02 14:27 UTC, anton7811 requested changes

2023-02-02 14:27 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_wrong_fcs.py
> +import pytest
You can move this file to the test_bridging_forwarding.py

2023-02-02 14:27 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_wrong_fcs.py
> +pytestmark = [pytest.mark.suite_functional_bridging, pytest.mark.asyncio]
Please write each mark from a new line.

2023-02-02 14:27 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_wrong_fcs.py
> +    8.  Verify that address haven't been learned due to wrong frame check sequence in packet.
Haven't been learned and haven't been forwarded.

2023-02-02 14:27 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_wrong_fcs.py
> +    # check the traffic stats
Check that traffic is not forwarded as well.
But for the fowarding, you should not disable flooding.

2023-02-02 14:27 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_wrong_fcs.py
> +    err_msg = f"Verify that bridge set to 'UP' state.\n{out}"
IMO there is no reason to use a separate variable here. It is used only once in the next line.

2023-02-02 14:27 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_learning_illegal_address.py
> +        "bridge_1": {
Maybe give more clear names. E.g.:  "all_zeros", "multicast", "broadcast", etc.

2023-02-02 14:27 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_static_entries.py
> +pytestmark = [pytest.mark.suite_functional_bridging, pytest.mark.asyncio]
Please write each mark from a new line.

2023-02-02 14:27 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_static_entries.py
> +    Test Overview: Verify static bridge entries.
"static FDB entries"

2023-02-02 14:27 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_static_entries.py
> +    out = await IpLink.add(
You can move your bridge setup to a fixture and use it on the module level. Anyway each test require it.

2023-02-02 16:16 UTC, SerhiyBoikoPLV requested changes
Please rebase your changes onto `master` and please use cleanup fixtures in your tests.

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_ageing.py
> +    Test Overview: Verify that bridge learning entries appear with continues traffic after ageing time expired.
```suggestion
    Test Overview: Verify that bridge learning entries appear with continuous traffic after ageing time expired.
```

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_ageing.py
> +    8.  Continues traffic sending to swp1, swp2, swp3, swp4 with sourse macs
```suggestion
    8.  Send continuous traffic to swp1, swp2, swp3, swp4 with sourse macs 
```

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_admin_state_down_up.py
> +    await tgen_utils_stop_protocols(tgen_dev)
use `cleanup_tgen` instead

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_jumbo_frame.py
> +            {"device": port, "master": bridge, "mtu": 9000} for port in ports]}])
You should restore the default MTU after the test run. Moreover, this should be done in a way that will restore the default value even if the test fails/crashes. You can use a fixture or a try-finally to do this.

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_jumbo_frame.py
> +async def test_bridging_frame_min(testbed):
```suggestion
async def test_bridging_jumbo_frame_min_size(testbed):
```

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_jumbo_frame.py
> +        assert tgen_utils_get_loss(row) == 0.000, \
The first and second asserts are redundant. You should remove them and only keep the third assert.

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_learning.py
> +    assert out[0][device_host_name]["rc"] == 0, f"Verify that bridge, bridge entities set to 'UP' state and links enslaved to bridge.\n{out}"
```suggestion
    out = await IpLink.set(input_data=[{device_host_name:  [
        {"device": port, "master": "br0", "operstate": "up"} for port in ports
    ] + [
        {"device": bridge, "operstate": "up"}
    ]}])
    assert out[0][device_host_name]["rc"] == 0, \
        f"Verify operstate 'UP' and links enslaved to bridge.\n{out}"
```

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_learning.py
> +    assert out[0][device_host_name]["rc"] == 0, f"Verify that entities set to learning 'ON' and flooding 'OFF' state.\n{out}"
```suggestion
    assert out[0][device_host_name]["rc"] == 0, \
        f"Verify that entities set to learning 'ON' and flooding 'OFF' state.\n{out}" 
```

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_learning.py
> +        },
use a list comprehension as you did in your other test

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_learning.py
> +        assert addr in test_data_in, f"Verify that source mac aa:bb:cc:dd:ee:11,aa:bb:cc:dd:ee:12,aa:bb:cc:dd:ee:13,aa:bb:cc:dd:ee:14 have been learned.\n{out}"
```suggestion
        assert addr in test_data_in, \
            f"Verify that source macs have been learned.\n{out}"
```

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_learning.py
> +#BLOCKED#BLOCKED#BLOCKED#BLOCKED#BLOCKED#BLOCKED#BLOCKED#BLOCKED#BLOCKED#BLOCKED#BLOCKED#BLOCKED#BLOCKED#BLOCKED#BLOCKED#BLOCKED
```suggestion
# FIXME: *reason*
```

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_learning_illegal_address.py
> +   # check the traffic stats
```suggestion
    # check the traffic stats
```

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_packets.py
> +
2 newlines before and after a function

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_packets.py
> +async def get_port_stats(device_host_name, ports):
@SerhiyBoikoPLV need to think about moving this to common code

2023-02-02 16:16 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_static_entries.py
> +pytestmark = [pytest.mark.suite_functional_bridging, pytest.mark.asyncio]
```suggestion
pytestmark = [
    pytest.mark.suite_functional_bridging,
    pytest.mark.asyncio,
]
```

2023-02-03 23:28 UTC, closed without merging