Add lacp tests
PLVision/dent-testing pull request #151
Opened 2023-06-01 12:25 UTC by StepanVovkPLV

2023-06-13 05:14 UTC, SerhiyBoikoPLV requested changes

2023-06-13 05:14 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_distribution_over_ecmp.py
> +from dent_os_testbed.lib.os.sysctl import Sysctl
If this is used only for ipv4 forwarding then please use `enable_ipv4_forwarding` fixture instead and remove `Sysctl` import.
If this is used somewhere else then please use `RecoverableSysctl`:
```suggestion
from dent_os_testbed.lib.os.recoverable_sysctl import RecoverableSysctl
```

2023-06-13 05:14 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_bridge.py
> +        DUT port <==> Ixia port 1 to bond 1
```suggestion
        DUT port <==> TG port 1 to bond 1
```

2023-06-13 05:14 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_lacp.py
> +    2. Enslave DUT port <==> Ixia port 1 to bond1
```suggestion
    2. Enslave DUT port <==> TG port 1 to bond1
```

2023-06-13 05:14 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_vlan_device.py
> +    2. Enslave DUT port <==> Ixia port 1 to bond1
```suggestion
    2. Enslave DUT port <==> TG port 1 to bond1
```

2023-06-13 05:14 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_bridge.py
> +    # 5. Enable IPv4 forwarding
please use fixture to enable ipv4 forwarding (see ipv4 tests)

2023-06-13 05:14 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_bridge.py
> +    await tgen_utils_stop_traffic(tgen_dev)
redundant

2023-06-13 05:14 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_vlan_device.py
> +        'vlan_default_pvid': 10,
```suggestion
        'vlan_default_pvid': vid,
```

2023-06-13 05:14 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_vlan_device.py
> +    out = await BridgeVlan.add(input_data=[{dent: [{'device': bridge, 'vid': vid, 'self': True}]}])
This is redundant. Your bridge already has vlan 10 because you created the bridge with `'vlan_default_pvid': 10`

2023-06-19 07:42 UTC, yuriilisovskyi requested changes

2023-06-19 07:42 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_distribution_over_ecmp.py
> +
No need for 2 newlines here (1 is enough)

2023-06-19 07:42 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_distribution_over_ecmp.py
> +
No need for 2 newlines here (1 is enough)

2023-06-19 07:42 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_negative_acl_over_lag.py
> +    dent = device.host_name
Duplicate code line

2023-06-27 21:27 UTC, StepanVovkPLV commented
closed in favor of https://github.com/PLVision/dent-testing/pull/162

2023-06-27 21:27 UTC, closed without merging