Lacp new traffic tests
PLVision/dent-testing pull request #153
Opened 2023-06-14 16:29 UTC by StepanVovkPLV

2023-06-15 07:10 UTC, SerhiyBoikoPLV requested changes

2023-06-15 07:10 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_vrf.py
> +                                      'cleanup_bridges', 'cleanup_sysctl',
where are you using sysctl?

2023-06-15 07:10 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/cleanup_utils.py
> +    out = await IpRoute.show(
check for `rc`

2023-06-15 07:10 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/cleanup_utils.py
> +    )
check for `rc`

2023-06-15 07:10 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/conftest.py
> +async def cleanup_tables(testbed):
```suggestion
async def cleanup_vr_tables(testbed):
```

2023-06-15 07:10 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/cleanup_utils.py
> +    # pdb.set_trace
don't forget to remove this

2023-06-15 07:10 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_vrf.py
> +    tgen_lag_3 = ('LAG_2', tg_ports[2:])
suggestion: you can use the same name for the lags on ixia as the name for bonds on dut (bond_1, bond_2, ...)

2023-06-15 07:10 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_vrf_and_vlan_device.py
> +    assert out[0][dent]['rc'] == 0, 'Failed adding route'
why can't you first create two vrfs using one api call? why do you need to separate vrf1 and vrf2 calls?

2023-06-15 07:10 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_vrf_and_vlan_device.py
> +    assert out[0][dent]['rc'] == 0, f'Failed setting {bridge} as master for {bonds[2]}'
same here. this can all be done using a single api call

2023-06-19 07:38 UTC, yuriilisovskyi requested changes

2023-06-19 07:38 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_vrf.py
> +    vrfs = {
Make more informative variable name

2023-06-23 16:51 UTC, SerhiyBoikoPLV requested changes

2023-06-23 16:51 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_vrf.py
> +pytestmark = [pytest.mark.suite_funtional_lacp,
```suggestion
pytestmark = [pytest.mark.suite_functional_lacp,
```

2023-06-23 16:51 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_routing_over_vrf_and_vlan_device.py
> +pytestmark = [pytest.mark.suite_funtional_lacp,
```suggestion
pytestmark = [pytest.mark.suite_functional_lacp,
```

2023-06-23 16:51 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_with_all_vlan_modes.py
> +pytestmark = [pytest.mark.suite_funtional_lacp,
```suggestion
pytestmark = [pytest.mark.suite_functional_lacp,
```

2023-06-27 21:27 UTC, StepanVovkPLV commented
closed in favor of https://github.com/PLVision/dent-testing/pull/162

2023-06-27 21:27 UTC, closed without merging