Add lacp stp selecting root bridge test
PLVision/dent-testing pull request #156
Opened 2023-06-16 07:44 UTC by StepanVovkPLV

- Adds 2 test
 - Adds addition option `mstid `to MstPctl.set()

2023-06-19 07:24 UTC, yuriilisovskyi approved these changes

2023-06-29 07:52 UTC, SerhiyBoikoPLV requested changes

2023-06-29 07:52 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_select_root.py
> +                   'root-port'] != '', f'Bridge {bridge_names[1]} or {bridge_names[2]} is a root bridge'
```suggestion
        assert out[0][dent]['parsed_output'][0]['root-port'] != '', \
            f'Bridge {bridge_names[1]} or {bridge_names[2]} is a root bridge'
```

2023-06-29 07:52 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_select_root.py
> +    assert out[0][dent]['parsed_output'][0]['root-port'] == '', f'Bridge { bridge_names[2]} is a root bridge'
```suggestion
    assert out[0][dent]['parsed_output'][0]['root-port'] == '', f'Bridge {bridge_names[2]} is a root bridge'
```

2023-06-29 07:52 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_select_root.py
> +    # assert out[0][dent]['rc'] == 0, 'Failed to change priority of the bridge'  # RC = '-1', but command succeeds
uncomment or open issue

2023-07-05 13:05 UTC, StepanVovkPLV commented
https://github.com/PLVision/dent-testing/pull/164 all tests here

2023-07-05 13:05 UTC, closed without merging