Add lacp  stp interaction tests
PLVision/dent-testing pull request #163
Opened 2023-06-28 06:56 UTC by StepanVovkPLV

2023-06-29 07:45 UTC, SerhiyBoikoPLV requested changes

2023-06-29 07:45 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_blocked_port_stp_rstp.py
> +              pytest.mark.usefixtures('cleanup_tgen', 'cleanup_bonds', 'cleanup_bridges')]
```suggestion
              pytest.mark.usefixtures('cleanup_tgen', 'cleanup_bonds',
                                      'cleanup_bridges', 'enable_mstpd')]
```

2023-06-29 07:45 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_blocked_port_stp_rstp.py
> +    # assert out[0][dent]['rc'] == 0, 'Failed to change priority of the bridge'
uncomment or open an issue

2023-07-03 07:38 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_blocked_port_stp_rstp.py
> +              pytest.mark.usefixtures('cleanup_tgen', 'cleanup_bonds', 'cleanup_bridges', 'enable_mstpd')]
You don't need cleanup_tgen fixture here since you don't set up any traffic there

2023-07-03 07:39 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_root_bridge_stp_rstp.py
> +              pytest.mark.usefixtures('cleanup_tgen', 'cleanup_bonds', 'cleanup_bridges', 'enable_mstpd')]
No need for cleanup_tgen

2023-07-03 07:39 UTC, yuriilisovskyi approved these changes

2023-07-05 14:34 UTC, SerhiyBoikoPLV requested changes

2023-07-05 14:34 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_blocked_port_stp_rstp.py
> +    out = await IpLink.set(input_data=[{dent: [{'device': bond, 'master': port}]} for port, bond in bonds.items()])
`bonds` is a dict of 'bond name' = 'slave name':
```python
bonds[f'bond_{idx+1}'] = port
bonds.items()  # ((f'bond_{idx+1}', port), ...)
```
but you are using the wrong naming here:
```suggestion
    out = await IpLink.set(input_data=[{dent: [{'device': port, 'master': bond}]} for bond, port in bonds.items()])
```

2023-07-05 14:34 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_root_bridge_stp_rstp.py
> +        'root-port'] == '', f'Bridge {bridge_names[2]} is not a root bridge'
```suggestion
    assert out[0][dent]['parsed_output'][0]['root-port'] == '', \
        f'Bridge {bridge_names[2]} is not a root bridge'
```

2023-07-08 14:27 UTC, SerhiyBoikoPLV requested changes

2023-07-08 14:27 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/lacp/test_lacp_blocked_port_stp_rstp.py
> +pytestmark = [pytest.mark.suite_functional_devlink,
```suggestion
pytestmark = [pytest.mark.suite_functional_lacp,
```
Please make sure that you change this in all of your tests
```

<Package lacp>
  <Module test_lacp_blocked_port_stp_rstp.py>
    <Function test_lacp_root_port[rstp]>
    <Function test_lacp_root_port[stp]>
  <Module test_lacp_loopback_detection.py>
    <Function test_lacp_loopback_detection[rstp]>
    <Function test_lacp_loopback_detection[stp]>
  <Module test_lacp_root_bridge_stp_rstp.py>
    <Function test_lacp_root_bridge_selection_stp[stp]>
    <Function test_lacp_root_bridge_selection_stp[rstp]>
  <Module test_lacp_traffic_during_topology_convergence.py>
    <Function test_lacp_traffic_during_topology_convergence[stp]>
    <Function test_lacp_traffic_during_topology_convergence[rstp]>
```

2023-07-10 17:01 UTC, yuriilisovskyi approved these changes

2023-07-11 06:46 UTC, SerhiyBoikoPLV approved these changes

2023-07-20 07:30 UTC, merged