Add stp root tests
PLVision/dent-testing pull request #164
Opened 2023-06-28 12:13 UTC by StepanVovkPLV

2023-06-29 07:55 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_select_root.py
> +    # assert out[0][dent]['rc'] == 0, 'Failed to change priority of the bridge'  # RC = '-1', but command succeeds
uncomment or open an issue

2023-07-03 07:48 UTC, yuriilisovskyi approved these changes

2023-07-05 14:46 UTC, SerhiyBoikoPLV requested changes

2023-07-05 14:46 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_ports.py
> +    rc, _ = await dent_device.run_cmd(f'ifconfig {bridge} hw ether 22:BB:4D:85:E7:098')
it is better to use `IpLink.set()` to change the mac addr

2023-07-05 14:46 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_ports.py
> +    await tgen_utils_stop_traffic(tgen_dev)
redundant

2023-07-05 14:46 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_select_root.py
> +@pytest.mark.parametrize('version', ['stp', 'rstp'])
You are using this in every test in this file. You can move this to `pytestmark` at L22 and remove this from all tests.

2023-07-05 14:46 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/stp/test_stp_with_traffic.py
> +        version = choice(['stp', 'rstp'])
as discussed with @yuriilisovskyi - change the test steps 6-8 to be:
1) switch between STP-RSTP-STP
2) switch between RSTP-STP-RSTP
Choose either one or make the test parametrized and run both scenarios.

2023-07-10 17:06 UTC, yuriilisovskyi approved these changes

2023-07-11 06:52 UTC, SerhiyBoikoPLV approved these changes

2023-07-20 11:08 UTC, merged