Add VLAN tagged packet size test
PLVision/dent-testing pull request #32
Opened 2023-02-03 13:14 UTC by StepanVovkPLV

Add  `test_vlan_tagged_packet_size` test
Signed-off-by: Stepan Vovk <stepan.vovk@plvision.eu>

2023-02-03 13:28 UTC, SerhiyBoikoPLV requested changes

2023-02-03 13:28 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_packets.py
> +
```suggestion
        "frameSize": 512,
    }}

```

2023-02-03 13:28 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_packets.py
> +    assert tagged_traffic_size - untagged_traffic_size == 4, f"Expected difference in 4 bytes"
```suggestion
    expected_packet_size = streams["Untagged traffic"].get("frameSize")
    for row in stats.Rows:
        actual_packet_size = int(row["Rx Bytes"]) / int(row["Rx Frames"])
        if row["Rx Port"] == tg_ports[tagged_traffic_port]:
            assert actual_packet_size == expected_packet_size + 4 \
                f"Expected packet size to be {expected_packet_size + 4}, but actual size is {actual_packet_size}"
        else:
            assert actual_packet_size == expected_packet_size \
                f"Expected packet size to be {expected_packet_size}, but actual size is {actual_packet_size}"
```

2023-02-06 11:15 UTC, SerhiyBoikoPLV approved these changes

2023-02-07 20:26 UTC, anton7811 requested changes

2023-02-07 20:26 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_packets.py
> +    Test Overview: Test packet with VLAN tag on untagged port is bigger by 4 bytes
How can we observe tagged packets on an untagged port? Please correct this statement.

2023-02-07 20:26 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/vlan/test_vlan_packets.py
> +    expected_packet_size = streams["Untagged traffic"].get("frameSize")
"actual" and "expected" are a little bit confusing. Especially when you compare with expected + 4. I suggest to use tx_frame_size and rx_frame_size.

2023-02-15 16:51 UTC, anton7811 approved these changes

2023-02-22 10:34 UTC, closed without merging