Add ACL tests
PLVision/dent-testing pull request #36
Opened 2023-02-08 09:51 UTC by SerhiyBoikoPLV

Tests:
- test_acl_addition_deletion_under_traffic
- test_acl_rule_deletion
- test_acl_rule_without_qdisk
- test_acl_skip_sw_hw_selector[action=pass]
- test_acl_skip_sw_hw_selector[action=drop]

Update suite groups.
Update tcutil_tc_rules_to_tgen_streams function.
Update LinuxTcFilterImpl class.

Signed-off-by: Serhiy Boiko <serhiy.boiko@plvision.eu>

2023-02-09 08:28 UTC, StepanVovkPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/acl/test_acl.py
> +import pdb
probably need to be removed?

2023-03-01 18:04 UTC, yuriilisovskyi approved these changes

2023-03-03 14:03 UTC, anton7811 requested changes

2023-03-03 14:03 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/acl/test_acl.py
> +    Test Overview: Test ACL functionality
You have the same description in all tests. Could you please briefly define the test purpose in each one?

2023-03-03 14:03 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/acl/test_acl.py
> +        "type": "raw",
You are adding a rule for ip proto. Maybe here it's better to set type: ipv4?

2023-03-03 14:03 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tc_flower_utils.py
> +def tcutil_tc_rules_to_tgen_streams(swp_tc_rules, streams=None, start=0, cnt=None,
Docstring?

2023-03-03 14:03 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tc_flower_utils.py
> +async def tcutil_verify_ixia_stats(dev, row, rule_action="pass",
Let's rename to `tcutil_verify_tgen_stats`

2023-03-06 09:15 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/acl/test_acl.py
> +        "type": "raw",
changed the tc rule

2023-03-06 10:59 UTC, anton7811 approved these changes

2023-03-29 08:16 UTC, closed without merging