add bridging tests
PLVision/dent-testing pull request #37
Opened 2023-02-09 00:31 UTC by stavrukPLV

Signed-off-by: Kostiantyn Stavruk <kostiantyn.stavruk@plvision.eu>

2023-02-21 13:08 UTC, SerhiyBoikoPLV requested changes
Please rebase your changes on top of the latest master branch

2023-02-21 13:08 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +                               parse_output=True)
pep8
```suggestion
    out = await IpLink.show(input_data=[{device_host_name: [{"device": ports[0], "options": "-j"}]}],
                            parse_output=True)
```

2023-02-21 13:08 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +            "dstPort": str(179),
```suggestion
            "dstPort": "179",
```

2023-02-21 13:08 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +        if row["Traffic Item"] == "Bridged_UnknownL2UC" and row["Rx Port"] == tg_ports[1]:
Your rx port will always be tg_ports[1]. You don't specify any other ip_destination in your streams.
```suggestion
        if row["Traffic Item"] == "Bridged_UnknownL2UC":
```

2023-02-21 13:08 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +        if row["Traffic Item"] == "Bridged_UnknownL2UC" and row["Rx Port"] == tg_ports[1]:
Moreover, this is a lot of duplicate code. Consider using a dict:
```python
expected_loss = {
    "Traffic item 1": 0,
    "Traffic item 2": 100,
    ...
}
...
for row in stats.Rows:
    assert tgen_utils_get_loss(row) == expected_loss[row["Traffic Item"]], \
        "A beautiful error message"
```

2023-02-21 13:08 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +    assert int(count_of_packets[2][0]) == 0, f"Verify that packets dropped by kernel.\n"
Don't expect that your matches will be in order. It is better to use a loop:
```suggestion
    count_of_packets = re.findall(r"(\d+) packets (captured|received|dropped)", data)
    for count, type in count_of_packets:
        if type == "captured" or type == "received":
            assert int(count) > 0, f"Verify that packets are captured and received.\n"
        if type == "dropped":
            assert int(count) == 0, f"Verify that packets are dropped by kernel.\n"
```

2023-02-21 13:08 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_port_with_rif.py
> +    print(("TCPDUMP: packets=%s" % tcpdump.result()))
use .format() or f-string:
```suggestion
    print(f"TCPDUMP: packets={tcpdump.result()}")
```

2023-02-21 13:08 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_port_with_rif.py
> +    out = await IpAddress.delete(
What if your test fails earlier and you won't remove the ip addrs?

2023-02-21 13:08 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_learning_address_rate.py
> +                   "count": 1000},
```suggestion
            "srcMac": {"type": "increment",
                       "start": "00:00:00:00:00:35",
                       "step": "00:00:00:00:10:00",
                       "count": 1000},
```

2023-02-21 13:08 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_learning_address_rate.py
> +    9.  Verify that there was not flooding to swp3.
how are you checking this in the test?

2023-02-21 13:08 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_unregistered_traffic.py
> +        f"Verify that traffic from {row['Tx Port']} to {row['Rx Port']} forwarded.\n{out}"
```suggestion
        assert tgen_utils_get_loss(row) == 0.000, \
            f"Verify that traffic from {row['Tx Port']} to {row['Rx Port']} forwarded.\n{out}"
```

2023-02-21 13:08 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/utils/test_utils/tgen_utils.py
> +            assert out[0][device.host_name]["rc"] == 0, f"Setting tgen traffic failed.\n{out}"
don't forget that changes in this file (and other files) belong to a different PR and should not be included in the bridging tests PR

2023-02-21 13:08 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/ip/linux/linux_ip_link_impl.py
> +        cmd = "ip {} link {} ".format(params.get("options", ""), command)
As discussed, this change should not be done.

2023-02-22 09:57 UTC, yuriilisovskyi requested changes

2023-02-22 09:57 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +    }
These streams are present in each test. Is there a way to move it to another file and use the needed streams in each test? You can just update ip_source and ip_destination.

2023-02-27 14:47 UTC, anton7811 requested changes

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +    dev_groups = tgen_utils_dev_groups_from_config(
Do we really need this step? Those IPs are not in use in the test case. Can we pass an empty config?

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +        # # TODO: FIX
What is the problem with this one?

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +        "BridgedLLDP": {
LLDP with IP src/dst options?

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +        #  # TODO: FIX
Is this the issue with LLC frames? Do we have a bug for it? Why we can send LACP and cannot send this one?

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +            "dstIp": "1.1.1.3",
This is not a ME IP.

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +            "protocol": "ip",
Is this a correct field?

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +            "protocol": "0x0000",
Is this a correct protocol?

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +            "dstIp": "1.1.1.3",
Doesn't look like broadcast.

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +            "dstIp": "1.1.1.3",
Probably the idea was to test SSH to the DUT.

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +            "dstIp": "1.1.1.3",
Same comment  as for SSH.

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +        "Default_IPv4": {
What the stream is it?

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +            "dstIp": "1.1.1.3",
Also, there might be an idea to send traffic to the DUT

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +        "IPv4_AllSysInSubnet": {
What is this?

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +        "IPv4_AllRoutersInSubnet": {
Looks like multicast (this one and the previous one) But it is not a multicast.

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_with_rif.py
> +    }
Please review ALL streams.

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_bum_traffic_bridge_without_rif.py
> +    streams = {
In general, I would put all those tests in a single module and reuse these streams configurations. Otherwise, there are too many duplications.

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_forward_block_different_packets.py
> +            "dstIp": "1.1.1.3",
I have a doubt that the packet is correct.
Common comment:
After you have configured a stream, go to the IxNetwork GUI and check it. If the stream is invalid, GUI may give you a hit about what is not correct.

2023-02-27 14:47 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/bridging/test_bridging_learning_address_rate.py
> +            assert tgen_utils_get_loss(row) == 0.000, \
How can it be forwarded if no flooding and not FDB entries?

2023-03-02 18:16 UTC, closed without merging