Add L1 forced speed test(s)
PLVision/dent-testing pull request #41
Opened 2023-02-16 21:56 UTC by StepanVovkPLV

2023-02-20 09:10 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/constants.py
> +        "suite_functional_l1"
```suggestion
        "suite_functional_l1",
```

2023-02-20 09:26 UTC, SerhiyBoikoPLV requested changes
Please make sure that you are restoring the default speed/duplex after the test (by using a fixture or a try-catch-finally)

2023-02-20 09:26 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_forced_speed.py
> +                         ])
```suggestion
@pytest.mark.parametrize(
    "speed, duplex",
    [# (10, "full"), (10, "half"),
     # (100, "full"), (100, "half"),
     # (1000, "full"), (1000, "half"),
     (10000, "full")],
)
```

2023-02-20 09:26 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_forced_speed.py
> +                         ])
How are you going to test 10/100/1000 speed?

2023-02-20 09:26 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_forced_speed.py
> +                         ])
Another issue is that running each test would take a long time. Consider testing both full and half duplex during a single test run (10 full+half, 100 full+half, 1000 full, 10_000 full)

2023-02-20 09:26 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_forced_speed.py
> +        "speed": 10000,
use a variable

2023-02-20 11:17 UTC, anton7811 requested changes

2023-02-20 11:17 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_forced_speed.py
> +    model = await OnlpSystemInfo.show(input_data=[{device_host_name: [{}]}], parse_output=True)
Please move device type recognition to the fixture and skip the test if it is not applicable.

2023-02-20 11:17 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_forced_speed.py
> +        print.error("The testbed does not have enough dent with tgen connections")
What is this? There is no such attribute in print.

2023-02-20 11:17 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_forced_speed.py
> +    if "AS5114" not in switch and speed < 1000:
I suggest adding some external (e.g. YAML) file with models and port types. Please do not hardcode model names in test's code.

2023-02-20 11:17 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_forced_speed.py
> +    2. Create bridge entity
Do you relly need a bridge in this test scenario?

2023-02-20 11:17 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_forced_speed.py
> +    # TODO Add support for hals duplex streams
The most TODO here is to switch TG to a required speed/duplex mode.

2023-02-20 11:17 UTC, anton7811 commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_forced_speed.py
> +    await tgen_utils_start_traffic(tgen_dev)
Why do you send traffic two times?

2023-03-14 09:54 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/L1/test_l1_autodetect.py
> +    await asyncio.sleep(60)  # wait needed in case port was down before
Why do you wait 60 seconds here, but in other tests 20 seconds?

2023-03-20 13:54 UTC, yuriilisovskyi approved these changes

2023-04-10 10:15 UTC, closed without merging