Update bridge_link_impl, bridge_mdb_impl, ip_link_impl
PLVision/dent-testing pull request #49
Opened 2023-02-21 10:25 UTC by AndriyLozovyyPLV

Updated linux_bridge_link_impl.py, added missing parameter: `fastleave`.
Updated linux_bridge_mdb_impl.py, added missing parametrs: `device, port, group, vid` and funtion to `parse_output`. 
Updated linux_ip_link_impl.py, added missing parametrs: `type, mcast_snooping, mcast_igmp_version, mcast_querier, mcast_querier_interval`.

2023-02-21 10:28 UTC, SerhiyBoikoPLV requested changes

2023-02-21 10:28 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/bridge/linux/linux_bridge_mdb_impl.py
> +            cmd += "dev {} ".format(params["device"])
please use `dev` instead of `device`
```suggestion
        if "dev" in params:
            cmd += "dev {} ".format(params["dev"])
```

2023-02-22 08:50 UTC, SerhiyBoikoPLV approved these changes

2023-02-22 09:41 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbedLib/src/dent_os_testbed/lib/bridge/linux/linux_bridge_mdb_impl.py
> +        mdb_entry_type = "permanent" if params.get("permanent", "") else "temp"
Can be simplified into:
`mdb_entry_type = params.get("permanent", "temp")`

2023-02-22 14:57 UTC, anton7811 approved these changes

2023-04-07 07:04 UTC, closed without merging