IGMP snooping tests without traffic
PLVision/dent-testing pull request #61
Opened 2023-03-01 18:03 UTC by AndriyLozovyyPLV

Added IGMP snooping test cases without traffic:
- test_igmp_snooping[2-2]
- test_igmp_snooping[3-3]
- test_igmp_snooping[2-1]
- test_igmp_snooping[3-1]
- test_igmp_snooping[3-2]
- test_igmp_snooping_modified_query
- test_igmp_snooping_diff_source_addrs

2023-03-02 08:06 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/igmp/test_igmp_snooping.py
> +    dev_name = dent_dev.host_name
```suggestion
    dev_name = dent_devices[0].host_name
```

2023-03-02 08:09 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/igmp/test_igmp_snooping.py
> +                {"device": bridge, "type": "bridge", "mcast_querier_interval": querier_interval * 100}]}])
you can combine this with the previous command

2023-03-07 08:39 UTC, yuriilisovskyi requested changes

2023-03-07 08:39 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/igmp/test_igmp_snooping.py
> +        Dictinary with parsed mdb and router entries
Dictionary*

2023-03-07 08:39 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/igmp/test_igmp_snooping.py
> +        igm_ver (int): IGMP Version to set on bridge dev
igmp_ver

2023-03-28 08:56 UTC, closed without merging