Add Port Isolation basic functionality test
PLVision/dent-testing pull request #80
Opened 2023-03-16 07:38 UTC by stavrukPLV

**This includes:**

- test_port_isolation_basic_functionality.py
- constants.py
- __init__.py

2023-03-17 13:34 UTC, yuriilisovskyi requested changes

2023-03-17 13:34 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_basic_functionality.py
> +        print("The testbed does not have enough dent with tgen connections")
Convert it to pytest.skip()

2023-03-17 13:34 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_basic_functionality.py
> +    device_host_name = dent_dev.host_name
device_host_name = dent_devices[0].host_name

2023-03-17 13:34 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_basic_functionality.py
> +        if x >= 1:
It can be a simple "else" since this condition will be True if x != 0

2023-03-21 10:02 UTC, SerhiyBoikoPLV requested changes

2023-03-21 10:02 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_basic_functionality.py
> +        pytest.skip()("The testbed does not have enough dent with tgen connections")
```suggestion
        pytest.skip("The testbed does not have enough dent with tgen connections")
```

2023-03-21 10:02 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_basic_functionality.py
> +        {"device": ports[x], "isolated": True} for x in range(3)]}])
```suggestion
        {"device": port, "isolated": True} for port in ports[:3]]}])
```

2023-03-21 10:02 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_basic_functionality.py
> +                "ip_destination": dev_groups[tg_ports[(3-x) if x<2 else 0]][0]["name"],
please add a comment that describes what is the source and destination ports for each stream and for each `x`

2023-03-21 10:02 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_basic_functionality.py
> +                    "Verify that traffic is forwarded/not forwarded in accordance."
Only the dict is changing. Everything else can be moved outside the `if` block:
```suggestion
        if x == 0:
            expected_loss = {
                "stream0": 0,
                "stream1": 0,
                "stream2": 0,
                "stream3": 0,
            }
        else:
            expected_loss = {
                "stream0": 100,
                "stream1": 100,
                "stream2": 100,
                "stream3": 0,
            }
        # check the traffic stats
        stats = await tgen_utils_get_traffic_stats(tgen_dev, "Flow Statistics")
        for row in stats.Rows:
            assert tgen_utils_get_loss(row) == expected_loss[row["Traffic Item"]], \
                "Verify that traffic is  forwarded/not forwarded in accordance."
```

2023-03-22 08:54 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_enable_disable_feature_under_ws_traffic.py
> +                "Verify that traffic is forwarded/not forwarded in accordance."
pep8
```suggestion
async def check_traffic_stats(stats, expected_loss):
    for row in stats.Rows:
        assert tgen_utils_get_loss(row) == expected_loss[row["Traffic Item"]], \
            "Verify that traffic is forwarded/not forwarded in accordance."
```

2023-03-22 08:56 UTC, SerhiyBoikoPLV approved these changes

2023-03-30 23:06 UTC, yuriilisovskyi requested changes

2023-03-30 23:06 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_interaction_with_other_features_ports_inside_lag.py
> +async def del_bonds(out, device_host_name):
Make it a cleanup utility that can be generally used in other tests

2023-03-30 23:06 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_interaction_with_other_features_ports_inside_lag.py
> +async def test_port_isolation_interaction_with_other_features_ports_inside_lag(testbed):
Remove "_with_other_features"

2023-03-30 23:06 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_interaction_with_other_features_span_rule.py
> +    assert rc == 0, "Failed to delete tc filter."
Does it remove the previously created rule? I don't see setting pref value for ACL rules above

2023-03-30 23:06 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_interaction_with_other_features_span_rule.py
> +    assert rc == 0, "Failed to delete qdisc ingress."
It should be done by cleanup_qdiscs fixture

2023-03-30 23:06 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_interaction_with_other_features_storm_control.py
> +    assert rc == 0, "Failed to set unreg_mc_kbyte_per_sec_rate value 30277 kbps."
All devlink commands should be done by Devlink API which is introduced in PR #88. Try using it instead of cmd execution

2023-03-30 23:06 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_interaction_with_other_features_storm_control.py
> +        assert rc == 0, "Failed to set the unreg_mc_kbyte_per_sec_rate value to default."
It should be also converted to devlink cleanup fixture

2023-03-30 23:06 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_interaction_with_other_features_storm_control.py
> +        await tgen_utils_clear_traffic_items(tgen_dev)
I suggest moving it to cleanup_tgen fixture

2023-03-30 23:06 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_maximum_isolated_ports_on_bridge.py
> +    assert all(links_present), "Not all ports exist."
Create a generic function in tb_utils for it

2023-03-30 23:06 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_maximum_isolated_ports_on_bridge.py
> +    print(f"It took {datetime.now() - start_time} to grep count of entities.\n")
to verify ports presence*

2023-03-30 23:06 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_maximum_isolated_ports_on_bridge.py
> +    print(f"It took {datetime.now() - start_time} to set entities to 'UP' state.\n")
Create a generic function verify_all_ports_are_up in tb_utils

2023-03-30 23:06 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/port_isolation/test_port_isolation_stress_incremental_mac_addresses.py
Maybe we should create a separate "stress" suite and move this test there?

2023-04-10 19:22 UTC, closed without merging