Update infra1, infra2 config
PLVision/dent-testing pull request #83
Opened 2023-03-21 07:53 UTC by StepanVovkPLV

Update infra1, infra2 config

2023-03-21 09:51 UTC, SerhiyBoikoPLV approved these changes

2023-03-22 08:42 UTC, yuriilisovskyi requested changes

2023-03-22 08:42 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_infra1/testbed.json
> +                ["10.36.118.199:2:4", "infra2:swp36", "copper"]
What about old links? As I understand, we do still have swp1-4 connected to Ixia card #1. Can we leave them here and just add new links?

2023-03-22 08:42 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_infra1/testbed.json
> +                ["10.36.118.199:2:4", "infra2:swp36", "copper"]
Also, you have infra2 here, although it is infra1 config

2023-03-22 15:09 UTC, StepanVovkPLV commented on DentOS_Framework/DentOsTestbed/configuration/testbed_config/basic_infra1/testbed.json
> +                ["10.36.118.199:2:4", "infra2:swp36", "copper"]
> What about old links? As I understand, we do still have swp1-4 connected to Ixia card #1. Can we leave them here and just add new links?

I don't know the answer to it. How then in the test we will select which ports/card we need?

2023-03-28 11:51 UTC, yuriilisovskyi approved these changes

2023-04-21 08:06 UTC, closed without merging