Add IPv6 tests
PLVision/dent-testing pull request #86
Opened 2023-03-27 17:38 UTC by SerhiyBoikoPLV

Signed-off-by: Serhiy Boiko <serhiy.boiko@plvision.eu>

2023-03-30 23:31 UTC, yuriilisovskyi requested changes

2023-03-30 23:31 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_bridge.py
> +            f"Expected route to be one of {dut_routes}, not {route['dst']}"
I assume this piece of code is used in several places, move it to ipv6_utils.py

2023-03-30 23:31 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_bridge.py
> +        assert nei["state"] != "FAILED", "Unexpected neighbor state"
If it is used in several places, move it to utils

2023-03-30 23:31 UTC, yuriilisovskyi commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_bridge.py
> +async def test_ipv6_on_bridge_vlan(testbed):
Let's keep the rule "one file - one test" :)

2023-03-31 17:50 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_bridge.py
> +            f"Expected route to be one of {dut_routes}, not {route['dst']}"
moved to [ipv6_utils.py](https://github.com/PLVision/dent-testing/pull/86/files#diff-c406f4edaecdfea65f8c5ad01d9cf080349d2f0b6ef4662351c96105e6b2ad0b)

2023-03-31 17:50 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_bridge.py
> +        assert nei["state"] != "FAILED", "Unexpected neighbor state"
moved to [ipv6_utils.py](https://github.com/PLVision/dent-testing/pull/86/files#diff-c406f4edaecdfea65f8c5ad01d9cf080349d2f0b6ef4662351c96105e6b2ad0b)

2023-03-31 17:51 UTC, SerhiyBoikoPLV commented on DentOS_Framework/DentOsTestbed/src/dent_os_testbed/test/test_suite/functional/ipv6/test_ipv6_bridge.py
> +async def test_ipv6_on_bridge_vlan(testbed):
as discussed, similar tests will be kept in the same file

2023-04-03 18:49 UTC, yuriilisovskyi approved these changes

2023-04-10 07:11 UTC, closed without merging